// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team293.robot;

import org.usfirst.frc.team293.robot.commands.CloseClaw;
import org.usfirst.frc.team293.robot.commands.DriveStraightDistance;
import org.usfirst.frc.team293.robot.commands.OpenClaw;
import org.usfirst.frc.team293.robot.commands.SetElevatorPosition;
import org.usfirst.frc.team293.robot.commands.TurnThroughAngle;
import org.usfirst.frc.team293.robot.subsystems.Elevator;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class contains all the objects for the joysticks and joystick buttons

                   ,-'.,'`.                         ,'`.,'-.
                 ,'    `.OPEN CLAW          CLOSE CLAW,'    `.
               ,'        `-._   `'-~.,___,.~-'`   _,-'__      `.       _
              /   _____      '-.,_   _____   _,.-'   /  `.      \       |
             /  ,' ___ `.       ,',-'     `-.'.      |HIGH  __   \      |
            /  / ,' ' `. \    ,','           `.`.    `.__/ /  `.  \     |
           /   | |LEFT | |   / /     _   _     \ \    __   |MED2   \    |
          /    \ `DRIVE' /   |!  \/ |_) / \ \/  |!   /  `. `.__/    \   |
         /      `._____,'    |!  /\ |_) \_/ /\  |!   |MED1  __       \  | Elevator Positions
         !            ___    \ \               / /   `.__/ /  `.     |  |
         !         ,-'___`-.  `.`.           ,','          |LOW|     |  |
         |        / ,'   `. \   `.`-._____,-','       ___  `.__/     | _|
         |       | / -' '- \ | ,`             `.    ,'___`.          |
         |       | \ -. .- / |'                 `. / RIGHT \         |
         |        \ `.___,' /     ___     ___     `\ DRIVE /         |
         |         `-.___,-'     (___)   (___)      `.___.'          |
         |             ,'`-._                     _,-'`.             |
          \          ,'      `'~-.,_________,.-~'`      `.          /
           `.      ,'                                     `.      ,'
             `-__,'                                         `.__.'


 *
 */
public class OI {

    public Joystick gamepad = new Joystick(0);

    public JoystickButton getToteButton= new JoystickButton(gamepad,1);
    public JoystickButton getBinButton= new JoystickButton(gamepad,2);
    public JoystickButton liftToteButton = new JoystickButton(gamepad,3);
    public JoystickButton liftBinButton = new JoystickButton(gamepad,4);
    public JoystickButton highLiftButton = new JoystickButton(gamepad,11);


    public JoystickButton openClaw = new JoystickButton(gamepad,5);
    public JoystickButton closeClaw = new JoystickButton(gamepad,6);
    public JoystickButton openClamp = new JoystickButton(gamepad,7);
    public JoystickButton closeClamp = new JoystickButton(gamepad,8);

    /** Assigns the buttons and adds button to Smartdashboard */
    public OI() {

        SmartDashboard.putData("OpenClaw", new OpenClaw());
        SmartDashboard.putData("CloseClaw", new CloseClaw());
        SmartDashboard.putData("Turn 90 degrees", new TurnThroughAngle(90));
        SmartDashboard.putData("Drive 1 meter", new DriveStraightDistance(1));

        openClaw.whenPressed(new OpenClaw());
        closeClaw.whenPressed(new CloseClaw());

        getToteButton.whenPressed(new SetElevatorPosition(Elevator.getTote));
        liftToteButton.whenPressed(new SetElevatorPosition(Elevator.liftTote));
        getBinButton.whenPressed(new SetElevatorPosition(Elevator.getBin));
        liftBinButton.whenPressed(new SetElevatorPosition(Elevator.liftBin));
        highLiftButton.whenPressed(new SetElevatorPosition(Elevator.top));
    }
}