// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team293.robot.commands;

import org.usfirst.frc.team293.robot.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 * Closes the claw
 */
public class  CloseClaw extends Command {

    public CloseClaw() {
        requires(Robot.claw); //ensure the claw isn't being used elsewhere
    }

    protected void initialize() {
        setTimeout(1);
    }

    protected void execute() {
        Robot.claw.close();
    }

    /** If the contact sensor fails for some reason, the command will still time out after 1 second*/
    protected boolean isFinished() {
        return Robot.claw.hitObject() || isTimedOut();
    }

    protected void end() {
        //don't stop in simulation, because that would lose all grip in the arms
        //We will be fixing this for next year, I promise!
        if (Robot.isReal()){ 
            Robot.claw.stop();
        }
    }

    protected void interrupted() {
        end();
    }
}
