// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team293.robot.commands;

import org.usfirst.frc.team293.robot.Robot;

import edu.wpi.first.wpilibj.command.Command;

/**
 * Uses the two joysticks on an XBox gamepad to drive the robot
 */
public class  DriveWithGamepad extends Command {

    public DriveWithGamepad() {
        requires(Robot.driveTrain);
    }

    protected void initialize() {
    }

    protected void execute() {
        Robot.driveTrain.driveTank(Robot.oi.gamepad);
    }

    protected boolean isFinished() {
        return false;
    }

    protected void end() {
        Robot.driveTrain.stop();
    }

    protected void interrupted() {
        end();
    }
}
